### ISSUE TITLE
비밀번호 입력창 인식

### ISSUE THREAD

**Issue by laskcmd** [PragmoB/MomiCrack#2]
이거 비밀번호 입력하는 창을 열었는데 뒤에 아무일도 안 일어나는데 막힌건가요?

**Comment by PragmoB** [comment]
yes.
업데이트로 막힌거 맞고 맘먹고 뚫을라면 뚫을수도 있는데 인생낭비 같아서 그만뒀네요
앞으로도 다시 만질일은 없을듯
